- name: Copy file with owner and permissions
  hosts: teja
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /etc/ansible/copy.yml
        dest: /tmp
        owner: teja
        group: teja
        mode: '0644'

