---
- name: Install httpd and apache2 services
  hosts: teja
  become: yes

  tasks:
    - name: Install httpd
      yum: 
        name:  httpd
        state: present
        
      when: ansible_os_family == "RedHat"

    - name: Start and enable httpd on RedHat-based systems
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
  
    - name: Install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable apache2 on Debian-based systems
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

