--- 
- name: Install multiple packages
  hosts: teja
  become: yes

  vars:
    new_packages:
      - curl
      - tree
      
  tasks:
    - name: Install new required packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ new_packages }}"
