---
- name: Install and Configure Web Server
  hosts: 34.55.157.212
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      tags:
        - install

    - name: Start Apache Service
      service:
        name: apache2
        state: started
      tags:
        - service
     

    - name: Deploy Website Files
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        - deploy
    
    - name: Delete Apache2
      apt:
        name: apache2
        state: absent
      tags: 
        - delete

