---

- name: Install and Start the service   #- name indicates description
  hosts: localhost
  
  tasks:
  - name : Installing ngix
    yum:
     name: nginx
     state: present

  - name: Starting the nginx service
    service:
       name: nginx
       state: started
       enabled: true


