---
- name: Clone Git Repository to Remote Host
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure git is installed
      package:
        name: git
        state: present

    - name: Clone a Git repository
      git:
        repo: "https://github.com/ameda71/pullrepo.git"
        dest: "/opt/my_project"
        version: main
        update: yes
